### PR TITLE
Support `@type` plugin specifying annotation correctly

### LINKED ISSUE #9: ConfigExpander cannot treat `@type` plugin specifying notation
With 

* 'fluent-plugin-config-expander' version '0.1.5'
* Fluentd 0.12.20

I've got errors with following conf file:

```xml
<source>
  @type config_expander
  <config>
    @type tail
    format /..../
    path /var/log/access.log
    tag access.log.${hostname}
  </config>
</source>

<match example.**>
  @type config_expander
  <config>
    @type forward
    flush_interval 30s
    <for x in 01 02 03>
      <server>
        host worker__x__.local
        port 24224
      </server>
    </for>
  </config>
</match>
```

Errors:

```log
$ bundle exec fluentd -c fluent.conf -p lib/fluent/plugin/ 
2016-03-03 18:45:54 +0900 [info]: reading config file path="fluent.conf"
2016-03-03 18:45:54 +0900 [info]: starting fluentd-0.12.20
2016-03-03 18:45:54 +0900 [info]: gem 'fluentd' version '0.12.20'
2016-03-03 18:45:54 +0900 [info]: gem 'fluent-plugin-config-expander' version '0.1.5'
2016-03-03 18:45:54 +0900 [info]: adding match pattern="example.**" type="config_expander"
2016-03-03 18:45:54 +0900 [error]: config error file="fluent.conf" error="Unknown output plugin ''. Run 'gem search -rd fluent-plugin' to find plugins"
2016-03-03 18:45:54 +0900 [info]: process finished code=256
2016-03-03 18:45:54 +0900 [warn]: process died within 1 second. exit.
```

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes #9

### CODE REVIEW

**Comment by cosmo0920** [comment]
Should I add test for at-type notation?

**Comment by tagomoris** [comment]
It's enough for now... Thanks.

**Comment by tagomoris** [comment]
I've just released v0.2.0.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
